name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t adralx/docker-basic-graphql:0.0.1 .
        docker build -t adralx/docker-basic-graphql:latest .

    - name: Push Docker Image
      run: |
        docker push adralx/docker-basic-graphql:0.0.1
        docker push adralx/docker-basic-graphql:latest


#   - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


